apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanarch-deployment
  labels:
    app: cleanarch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanarch
  template:
    metadata:
      labels:
        app: cleanarch
    spec:
      containers:
      - name: cleanarch
        image: br.edu.ifmt/cleanarch
        imagePullPolicy: Never
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cleanarch-service
spec:
  selector:
    app: cleanarch
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 30000