version: '3.8'
services:
  cleanarch:
    image: br.edu.ifmt/cleanarch
    container_name: cleanarch
    ports:
      - '7070:7070'
    restart: always
    networks:
      - ifmt
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:7070/users"]
    #   interval: 4s
    #   timeout: 20s
    #   retries: 5

  cleanarch-cli: 
    image: br.edu.ifmt/cleanarch-cli
    stdin_open: true
    tty: true
    container_name: cleanarch-cli
    restart: unless-stopped
    networks:
      - ifmt
    depends_on:
      - cleanarch
networks:
  ifmt:
    external: true
