@uri=http://localhost:7070
@users={{uri}}/users

GET {{users}} HTTP/1.1

###
POST {{users}} HTTP/1.1
Content-Type: application/json

{
    "username": "joaopaulo",
    "email": "email@algo.com",
    "password": "admin"
}